### PR TITLE
Fix empty file_name case

### LINKED ISSUE #2: Empty file_name
If file_name is empty in {image_factory} display a 404 image instead of not-found-image

### PR DESCRIPTION
**Pull request by TomPradat**
Fix #2

### CODE REVIEW

File: Plugin/ImageFactorySmartyPlugin.php [hunk 1]
```diff
@@ -201,7 +201,11 @@ protected function resolveByFileName(FactoryEntity $factory, $params)
             $pathInfo = new PathInfo($fileName);
 
             foreach ($factory->getSources() as $source) {
-                $path = $source . DS . $pathInfo->getFilename() . '.' . $pathInfo->getExtension();
+                if ($pathInfo->getFilename()) {
+                    $path = $source . DS . $pathInfo->getFilename() . '.' . $pathInfo->getExtension();
+                } else {
+                    $path = '';
+                }
                 if (file_exists($path)) {
```
Comment (gillesbourgeat) [inline Plugin/ImageFactorySmartyPlugin.php]: And like that ?

``` php
        if ($pathInfo->getFilename()) {
            $path = $source . DS . $pathInfo->getFilename() . '.' . $pathInfo->getExtension();
            if (file_exists($path)) {
                $pathInfo = new PathInfo($path);
                $images[] = $this->generateImage(
                    $factory,
                    $params,
                    $pathInfo->getDirname() . DS . $pathInfo->getFilename() . '.' . $pathInfo->getExtension()
                );
                break;
            }
        }
```

Comment (TomPradat) [inline Plugin/ImageFactorySmartyPlugin.php]: It works as well, waiting for you to merge it :)

**Comment by gillesbourgeat** [comment]
Thanks !
